project:
  type: website
  output-dir: .
  
website:
  title: "Philippe Sloksnath"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    toc: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css">
        <link rel="stylesheet" href="styles.css">

